# Use postgres/example user/password credentials
version: '3.1'

services:

  supertokens:
    image: supertokens/supertokens-postgresql
    environment:
      POSTGRESQL_HOST: localhost
      POSTGRESQL_USER: postgres
      POSTGRESQL_PASSWORD: ppooii12
      POSTGRESQL_PORT: 5432
      POSTGRESQL_DATABASE_NAME: what-todo
    ports:
      - 3567:3567