// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Todo struct {
	ID        string `json:"_id" gorm:"primaryKey;column:_id"`
	Todo      string `json:"todo"`
	Done      bool   `json:"done"`
	CreatedAt string `json:"createdAt" gorm:"column:createdAt"`
}